[package]
name = "hsploit"
version = "0.1.0"
authors = ["user"]

[dependencies]
byteorder = "1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
kernel32-sys = "0.2.2"
psapi-sys = "0.1.1"
